data:
  rgb:
    url: https://www.wms.nrw.de/geobasis/wms_nw_dop
    layer: nw_dop_rgb
  nir:
    url: https://www.wms.nrw.de/geobasis/wms_nw_dop
    layer: nw_dop_nir
  epsg_code: 25832
  path_boundary:
  bounding_box:
    - 363210
    - 5715455
    - 364210
    - 5716455
  apply_padding: false
  ignore_processed_tiles: false

postprocessing:
  sieve_size: 2
  simplify: false

aggregation:
  tile_size:
    - 50
    - 100
  path_aggregation_areas:

export:
  path_output_dir: /Pfad/zu/Ausgabeverzeichnis
  prefix: prefix